[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "chinese-converter>=1.1.1",
    "beautifulsoup4~=4.12.2",
    "genanki~=0.13.0",
    "jieba~=0.42.1",
    "pinyin~=0.4.0",
    "requests~=2.31.0",
    "wordfreq",
]
build-backend = "setuptools.build_meta"
