[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "requests~=2.30.0",
    "pinyin~=0.4.0",
    "beautifulsoup4~=4.12.2",
    "genanki~=0.13.0",
    "jieba~=0.42.1",
]
build-backend = "setuptools.build_meta"